# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
